POST http://localhost:3000/videos
Content-Type: application/json

{
  "title": "Video 01",
  "description": "Este é o video 01",
  "duration": 180
}

###

GET http://localhost:3000/videos?search=node

###

PUT http://localhost:3000/videos/424bbe0a-9884-4a90-ba83-7397d936816a
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Este é o video 02",
  "duration": 180
}

###

DELETE http://localhost:3000/videos/fe9158e8-c219-4a85-ae37-484063538920
